#!/usr/bin/env bash

f () {
    ./bin/moon $1 $2 64
}


first=1

for parts in {1024,2048,4096,8192,16384,32768,65536}
do
    for blocksize in {8,16,32,64,128,256,512,1024}
    do
        f $parts $blocksize

        if [ $first == 1 ];
        then
            cat log | head -n 1 > sumlog
            first=0
        fi

        cat log | tail -n +2 >> sumlog
    done
done
